### ISSUE TITLE
Notification ?

### ISSUE THREAD

**Issue by daveit** [biancassilva/quasar-pomodoro-timer#1]
Hi Bianca, nice app, looking forward to checking out the code.
I'm not too familiar with Quasar, but I'm learning Vue.
And I really like the concept of Pomodoro, but the browser extensions I have seen have not been that good.
One question though?  There does not seem to be any notification or sound to end a period.
Is this something that is possible - else you simply miss the point and keep working :)
All the best, Dave

**Comment by biancassilva** [comment]
Hey Dave, thanks for your review! I really appreciate that. I forgot to put desktop notifications in my project but I already implemented the notifications and pushed it to the repository. Thank you!
